using System.Text;
using FluentAssertions;
using Xunit;

namespace SimpleSign.Pdf.Tests;

/// <summary>
/// Tests for PdfStructureReader with XRef streams, FlateDecode, and Object Streams.
/// </summary>
public sealed class PdfStructureReaderXrefTests
{
    // ── XRef streams (PDF 1.5+) ───────────────────────────────────────────────

    [Fact(DisplayName = "Finds signature in PDF with xref stream")]
    public async Task ReadSignatureFieldsAsync_XrefStreamPdf_FindsSignatureField()
    {
        // PDF with xref stream (generated by Word/LibreOffice/Acrobat DC)
        // The reader should find the signature field even without parsing the xref stream
        var pdf = BuildPdfWithXrefStream();
        using var stream = new MemoryStream(pdf);
        var reader = new PdfStructureReader();

        var fields = await PdfStructureReader.ReadSignatureFieldsAsync(stream);

        // Must find the signature field via brute-force scan even without classic xref
        fields.Should().ContainSingle(
            because: "signature field must be found in PDFs with cross-reference streams");
        fields[0].SubFilter.Should().Be("ETSI.CAdES.detached");
    }

    [Fact(DisplayName = "ByteRange is valid in PDF with xref stream")]
    public async Task ReadSignatureFieldsAsync_XrefStreamPdf_ByteRangeIsValid()
    {
        var pdf = BuildPdfWithXrefStream();
        using var stream = new MemoryStream(pdf);
        var reader = new PdfStructureReader();

        var fields = await PdfStructureReader.ReadSignatureFieldsAsync(stream);

        fields.Should().ContainSingle();
        fields[0].ByteRange.IsValid.Should().BeTrue(
            because: "ByteRange must be parseable regardless of xref format");
    }

    // ── FlateDecode xref streams (PDF 1.5+) ──────────────────────────────────

    [Fact(DisplayName = "Finds signature in PDF with FlateDecode xref")]
    public async Task ReadSignatureFieldsAsync_FlateDecodeXrefStream_FindsSignatureField()
    {
        var pdf = BuildPdfWithFlateDecodeXrefStream();
        using var stream = new MemoryStream(pdf);
        var reader = new PdfStructureReader();

        var fields = await PdfStructureReader.ReadSignatureFieldsAsync(stream);

        fields.Should().ContainSingle(
            because: "signature field must be found in PDFs with FlateDecode xref streams");
        fields[0].SubFilter.Should().Be("ETSI.CAdES.detached");
        fields[0].ByteRange.IsValid.Should().BeTrue();
    }

    // ── Object Streams (ObjStm / Type 2 xref entries) ────────────────────────

    [Fact(DisplayName = "Finds signature in PDF with Object Stream")]
    public async Task ReadSignatureFieldsAsync_XrefStreamWithObjStm_FindsSignatureField()
    {
        // PDF with xref stream using Type 2 entries (objects compressed inside ObjStm).
        // The signature dictionary itself is still a direct object (not in ObjStm)
        // because /ByteRange requires byte-addressable /Contents.
        // The ObjStm contains the Catalog and Pages objects.
        var pdf = BuildPdfWithObjectStream();
        using var stream = new MemoryStream(pdf);
        var reader = new PdfStructureReader();

        var fields = await PdfStructureReader.ReadSignatureFieldsAsync(stream);

        fields.Should().ContainSingle(
            because: "signature field must be found in PDFs using Object Streams with Type 2 xref entries");
        fields[0].SubFilter.Should().Be("ETSI.CAdES.detached");
        fields[0].ByteRange.IsValid.Should().BeTrue();
    }

    // ── Fixture helpers ───────────────────────────────────────────────────────

    /// <summary>
    /// PDF with xref stream (PDF 1.5+) containing a /Sig dictionary.
    /// The xref stream is uncompressed (no /Filter) for simplicity in testing.
    /// </summary>
    private static byte[] BuildPdfWithXrefStream()
    {
        var parts = new List<byte[]>();

        byte[] header = "%PDF-1.5\n"u8.ToArray();
        parts.Add(header);

        int obj1Off = header.Length;
        byte[] obj1 = "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"u8.ToArray();
        parts.Add(obj1);

        int obj2Off = obj1Off + obj1.Length;
        byte[] obj2 = "2 0 obj\n<< /Type /Pages /Kids [] /Count 0 >>\nendobj\n"u8.ToArray();
        parts.Add(obj2);

        int obj3Off = obj2Off + obj2.Length;
        string sigDictStr = "3 0 obj\n<< /Type /Sig /Filter /Adobe.PPKLite /SubFilter /ETSI.CAdES.detached\n" +
                            "/ByteRange [0 100 200 50]\n" +
                            "/Contents <" + "00".PadRight(20, '0') + ">\n" +
                            ">>\nendobj\n";
        byte[] obj3 = Encoding.ASCII.GetBytes(sigDictStr);
        parts.Add(obj3);

        int obj4Off = obj3Off + obj3.Length;

        // XRef stream (uncompressed, W=[1,3,1], 4 entries)
        // Entry format: [type(1)][offset(3)][gen(1)]
        byte[] xrefData = new byte[5 * 5]; // 5 entries × 5 bytes
        // obj 0: free
        xrefData[0] = 0;
        xrefData[1] = 0;
        xrefData[2] = 0;
        xrefData[3] = 0;
        xrefData[4] = 0xFF;
        // obj 1
        xrefData[5] = 1;
        xrefData[6] = (byte)(obj1Off >> 16);
        xrefData[7] = (byte)(obj1Off >> 8);
        xrefData[8] = (byte)obj1Off;
        xrefData[9] = 0;
        // obj 2
        xrefData[10] = 1;
        xrefData[11] = (byte)(obj2Off >> 16);
        xrefData[12] = (byte)(obj2Off >> 8);
        xrefData[13] = (byte)obj2Off;
        xrefData[14] = 0;
        // obj 3
        xrefData[15] = 1;
        xrefData[16] = (byte)(obj3Off >> 16);
        xrefData[17] = (byte)(obj3Off >> 8);
        xrefData[18] = (byte)obj3Off;
        xrefData[19] = 0;
        // obj 4 (xref itself)
        xrefData[20] = 1;
        xrefData[21] = (byte)(obj4Off >> 16);
        xrefData[22] = (byte)(obj4Off >> 8);
        xrefData[23] = (byte)obj4Off;
        xrefData[24] = 0;

        string xrefHdr = $"4 0 obj\n<< /Type /XRef /W [1 3 1] /Index [0 5] /Size 5 /Length {xrefData.Length} >>\nstream\n";
        byte[] xrefObj = Encoding.ASCII.GetBytes(xrefHdr);
        int xrefOff = obj4Off;
        parts.Add(xrefObj);
        parts.Add(xrefData);
        parts.Add("\nendstream\nendobj\n"u8.ToArray());

        string trailer = $"startxref\n{xrefOff}\n%%EOF";
        parts.Add(Encoding.ASCII.GetBytes(trailer));

        int totalLen = parts.Sum(p => p.Length);
        var result = new byte[totalLen];
        int pos = 0;
        foreach (var p in parts)
        { p.CopyTo(result, pos); pos += p.Length; }
        return result;
    }

    /// <summary>
    /// PDF with compressed xref stream (FlateDecode) containing a /Sig dictionary.
    /// </summary>
    private static byte[] BuildPdfWithFlateDecodeXrefStream()
    {
        var parts = new List<byte[]>();

        byte[] header = "%PDF-1.5\n"u8.ToArray();
        parts.Add(header);

        int obj1Off = header.Length;
        byte[] obj1 = "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"u8.ToArray();
        parts.Add(obj1);

        int obj2Off = obj1Off + obj1.Length;
        byte[] obj2 = "2 0 obj\n<< /Type /Pages /Kids [] /Count 0 >>\nendobj\n"u8.ToArray();
        parts.Add(obj2);

        int obj3Off = obj2Off + obj2.Length;
        string sigDictStr = "3 0 obj\n<< /Type /Sig /Filter /Adobe.PPKLite /SubFilter /ETSI.CAdES.detached\n" +
                            "/ByteRange [0 100 200 50]\n" +
                            "/Contents <" + "00".PadRight(20, '0') + ">\n" +
                            ">>\nendobj\n";
        byte[] obj3 = Encoding.ASCII.GetBytes(sigDictStr);
        parts.Add(obj3);

        int obj4Off = obj3Off + obj3.Length;

        // Build raw xref stream entries: W=[1,3,1], 5 entries (objects 0-4)
        byte[] xrefData = new byte[5 * 5];
        xrefData[0] = 0;
        xrefData[1] = 0;
        xrefData[2] = 0;
        xrefData[3] = 0;
        xrefData[4] = 0xFF; // free
        xrefData[5] = 1;
        xrefData[6] = (byte)(obj1Off >> 16);
        xrefData[7] = (byte)(obj1Off >> 8);
        xrefData[8] = (byte)obj1Off;
        xrefData[9] = 0;
        xrefData[10] = 1;
        xrefData[11] = (byte)(obj2Off >> 16);
        xrefData[12] = (byte)(obj2Off >> 8);
        xrefData[13] = (byte)obj2Off;
        xrefData[14] = 0;
        xrefData[15] = 1;
        xrefData[16] = (byte)(obj3Off >> 16);
        xrefData[17] = (byte)(obj3Off >> 8);
        xrefData[18] = (byte)obj3Off;
        xrefData[19] = 0;
        xrefData[20] = 1;
        xrefData[21] = (byte)(obj4Off >> 16);
        xrefData[22] = (byte)(obj4Off >> 8);
        xrefData[23] = (byte)obj4Off;
        xrefData[24] = 0;

        // Compress with zlib (2-byte header + deflate)
        byte[] compressedData;
        using (var ms = new MemoryStream())
        {
            // zlib header: CMF=0x78, FLG=0x9C (deflate, level default)
            ms.WriteByte(0x78);
            ms.WriteByte(0x9C);
            using (var deflate = new System.IO.Compression.DeflateStream(ms, System.IO.Compression.CompressionLevel.Optimal, leaveOpen: true))
            {
                deflate.Write(xrefData);
                deflate.Flush();
            }
            compressedData = ms.ToArray();
        }

        string xrefHdr = $"4 0 obj\n<< /Type /XRef /W [1 3 1] /Index [0 5] /Size 5 /Filter /FlateDecode /Length {compressedData.Length} >>\nstream\n";
        parts.Add(Encoding.ASCII.GetBytes(xrefHdr));
        parts.Add(compressedData);
        parts.Add("\nendstream\nendobj\n"u8.ToArray());

        string trailer = $"startxref\n{obj4Off}\n%%EOF";
        parts.Add(Encoding.ASCII.GetBytes(trailer));

        int totalLen = parts.Sum(p => p.Length);
        var result = new byte[totalLen];
        int pos = 0;
        foreach (var p in parts)
        { p.CopyTo(result, pos); pos += p.Length; }
        return result;
    }

    /// <summary>
    /// Builds a PDF with an Object Stream (ObjStm) containing the Catalog and Pages objects,
    /// referenced via Type 2 xref entries. The signature dictionary is a direct object (Type 1).
    /// </summary>
    private static byte[] BuildPdfWithObjectStream()
    {
        var parts = new List<byte[]>();

        byte[] header = "%PDF-1.5\n"u8.ToArray();
        parts.Add(header);

        // Object 3 = ObjStm containing objects 1 (Catalog) and 2 (Pages)
        // ObjStm format: header pairs "objNum offset objNum offset", then object data
        string catalogData = "<< /Type /Catalog /Pages 2 0 R >>";
        string pagesData = "<< /Type /Pages /Kids [] /Count 0 >>";
        // Header: "1 0 2 <len1>" where 0 and <len1> are byte offsets within the data portion
        int firstObjDataLen = catalogData.Length + 1; // +1 for space separator
        string objStmHeader = $"1 0 2 {firstObjDataLen}";
        string objStmContent = $"{objStmHeader}{catalogData} {pagesData}";
        int firstOffset = objStmHeader.Length; // /First points to where the data starts

        int obj3Off = header.Length;
        string obj3Str = $"3 0 obj\n<< /Type /ObjStm /N 2 /First {firstOffset} /Length {objStmContent.Length} >>\nstream\n{objStmContent}\nendstream\nendobj\n";
        byte[] obj3 = Encoding.ASCII.GetBytes(obj3Str);
        parts.Add(obj3);

        // Object 4 = Signature dictionary (direct object, Type 1)
        int obj4Off = obj3Off + obj3.Length;
        string sigDictStr = "4 0 obj\n<< /Type /Sig /Filter /Adobe.PPKLite /SubFilter /ETSI.CAdES.detached\n" +
                            "/ByteRange [0 100 200 50]\n" +
                            "/Contents <" + "00".PadRight(20, '0') + ">\n" +
                            ">>\nendobj\n";
        byte[] obj4 = Encoding.ASCII.GetBytes(sigDictStr);
        parts.Add(obj4);

        // Object 5 = xref stream
        int obj5Off = obj4Off + obj4.Length;

        // Xref entries: W=[1 3 1], 6 entries (objects 0-5)
        byte[] xrefData = new byte[6 * 5];
        // obj 0: free
        xrefData[0] = 0;
        xrefData[1] = 0;
        xrefData[2] = 0;
        xrefData[3] = 0;
        xrefData[4] = 0xFF;
        // obj 1: Type 2 (in ObjStm 3, index 0)
        xrefData[5] = 2;
        xrefData[6] = 0;
        xrefData[7] = 0;
        xrefData[8] = 3;
        xrefData[9] = 0;
        // obj 2: Type 2 (in ObjStm 3, index 1)
        xrefData[10] = 2;
        xrefData[11] = 0;
        xrefData[12] = 0;
        xrefData[13] = 3;
        xrefData[14] = 1;
        // obj 3: Type 1 (ObjStm itself)
        xrefData[15] = 1;
        xrefData[16] = (byte)(obj3Off >> 16);
        xrefData[17] = (byte)(obj3Off >> 8);
        xrefData[18] = (byte)obj3Off;
        xrefData[19] = 0;
        // obj 4: Type 1 (signature dictionary)
        xrefData[20] = 1;
        xrefData[21] = (byte)(obj4Off >> 16);
        xrefData[22] = (byte)(obj4Off >> 8);
        xrefData[23] = (byte)obj4Off;
        xrefData[24] = 0;
        // obj 5: Type 1 (xref stream itself)
        xrefData[25] = 1;
        xrefData[26] = (byte)(obj5Off >> 16);
        xrefData[27] = (byte)(obj5Off >> 8);
        xrefData[28] = (byte)obj5Off;
        xrefData[29] = 0;

        string xrefHdr = $"5 0 obj\n<< /Type /XRef /W [1 3 1] /Index [0 6] /Size 6 /Length {xrefData.Length} >>\nstream\n";
        byte[] xrefObj = Encoding.ASCII.GetBytes(xrefHdr);
        parts.Add(xrefObj);
        parts.Add(xrefData);
        parts.Add("\nendstream\nendobj\n"u8.ToArray());

        string trailer = $"startxref\n{obj5Off}\n%%EOF";
        parts.Add(Encoding.ASCII.GetBytes(trailer));

        int totalLen = parts.Sum(p => p.Length);
        var result = new byte[totalLen];
        int pos = 0;
        foreach (var p in parts)
        { p.CopyTo(result, pos); pos += p.Length; }
        return result;
    }
}
