using System.Diagnostics.CodeAnalysis;

namespace SimpleSign.Core.Inspection;

/// <summary>
/// Information extracted from an RFC 3161 timestamp token embedded in a CMS signature.
/// </summary>
[ExcludeFromCodeCoverage]
public sealed class TimestampInfo
{
    /// <summary>When the timestamp was generated by the TSA (GeneralizedTime from TSTInfo).</summary>
    public DateTimeOffset GenerationTime { get; init; }

    /// <summary>TSA certificate that signed the timestamp, if found in the token.</summary>
    public CertificateInfo? TsaCertificate { get; init; }

    /// <summary>Hash algorithm used in the timestamp's messageImprint.</summary>
    public AlgorithmInfo HashAlgorithm { get; init; } = new();

    /// <summary>TSA policy OID, if present in the TSTInfo.</summary>
    public string? PolicyOid { get; init; }

    /// <summary>Timestamp serial number in hexadecimal, if present.</summary>
    public string? SerialNumber { get; init; }

    /// <summary>Raw DER-encoded timestamp token bytes.</summary>
    public ReadOnlyMemory<byte> RawToken { get; init; }

    /// <inheritdoc />
    public override string ToString() =>
        TsaCertificate is not null
            ? $"Timestamp {GenerationTime:yyyy-MM-dd HH:mm:ss} by {TsaCertificate.Subject}"
            : $"Timestamp {GenerationTime:yyyy-MM-dd HH:mm:ss}";
}
